### ISSUE TITLE
[Compilation error][Not a bug] error C7525: inline variables require at least '/std:c++17'

### ISSUE THREAD

**Issue by harideva16** [axmetishe/gradle-qt-application-example#4] opened 2021-09-12 06:04 UTC
I download this project and run in my pc.
But , It comes an error like this 

[output.txt](https://github.com/axmetishe/gradle-qt-application-example/files/7149067/output.txt)

Why this error comes ?

How can I solve this error ?

**Comment by harideva16** [comment] 2021-09-12 06:12
I didn't know about how to solve this ?

How to config like this in build.gradle  `CONFIG += c++11`?

help me to solve this error !!!

**Comment by axmetishe** [comment] 2021-09-17 06:45
@harideva16 
https://github.com/axmetishe/gradle-qt-application-example/blob/master/build.gradle#L56 sets compiler standard for the MacOS platform.
https://github.com/axmetishe/gradle-qt-application-example/blob/master/build.gradle#L59 uses the same approach to define runtime libraries used in final product for Windows platform and this can be used to define the language standard.

- https://github.com/gradle/native-samples
- https://docs.gradle.org/current/userguide/building_cpp_projects.html
- https://docs.gradle.org/current/userguide/cpp_library_plugin.html
- https://docs.gradle.org/current/userguide/cpp_application_plugin.html

Regards

**Comment by harideva16** [comment] 2021-09-18 06:44
**I am using visual studio 2019**

If I create my project in qtcreater it works smoothly.

But ,If I run my qt project with this plugin it comes an error like this

    C:\Qt\6.1.3\mingw81_64\include\QtCore/qglobal.h(387): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qglobal.h(1261): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qglobal.h(1262): error C7525: inline variables require at least '/std:c++17'
    C:\Qt\6.1.3\mingw81_64\include\QtCore/qglobal.h(1263): error C7525: inline variables require at least '/std:c++17'
    The contents of <variant> are available only with C++17 or later.
    The contents of <optional> are available only with C++17 or later.


I am using windows os.

How can I solve this compilation error ?

I also asked in a  question stackoverflow https://stackoverflow.com/questions/69232205/the-contents-of-variant-are-available-only-with-c17-or-later.

I didn't know about how to solve this compilation error.

**Comment by axmetishe** [comment] 2021-09-18 07:03
Please read my comment above carefully, there are two links on code which has the exact settings you need.

**Comment by harideva16** [comment] 2021-09-18 12:23
> Please read my comment above carefully, there are two links on code which has the exact settings you need.

I tried the following code but the same compilation error.

    compileTask.compilerArgs.addAll toolChain.map { toolChain ->
        if (toolChain in VisualCpp) {
            return '/std=c++11'
        }
        return []
     }

**Comment by axmetishe** [comment] 2021-09-18 13:00
From the log above you should be already noticed that c++11 is not the standard you are looking for:
```
at least '/std:c++17'
```

**Comment by axmetishe** [comment] 2021-09-18 13:05
There's no need to specify VisualCpp toolchain additionally, you can use just:
```
if (compileTask.targetPlatform.get().operatingSystem.isWindows()) {
  compileTask.compilerArgs.add("/std:c++XX")
}
```

**Comment by harideva16** [comment] 2021-09-19 04:04
I tried  in github actions. it works smoothly in windows and linux.

but , it not worked in mac.

![qt red mark](https://user-images.githubusercontent.com/88296348/133915023-e20241ca-5122-4d6c-a2f0-fe17461aadba.PNG)

how can I solve this ?

**Comment by axmetishe** [comment] 2021-09-19 15:49
Execute Gradle with --stacktrace and place the output here please.

**Comment by harideva16** [comment] 2021-09-20 02:49
**output**

![exe](https://user-images.githubusercontent.com/88296348/133952795-781cc7a5-bae7-4015-93f6-9d901085a3ac.PNG)

**Comment by harideva16** [comment] 2021-09-20 03:35
**output files :**

[8_Execute build.txt](https://github.com/axmetishe/gradle-qt-application-example/files/7193517/8_Execute.build.txt)
[6_Verify Gradle Wrapper.txt](https://github.com/axmetishe/gradle-qt-application-example/files/7193518/6_Verify.Gradle.Wrapper.txt)
[7_Grant execute permission for gradlew.txt](https://github.com/axmetishe/gradle-qt-application-example/files/7193519/7_Grant.execute.permission.for.gradlew.txt)

**output**

![exe](https://user-images.githubusercontent.com/88296348/133952795-781cc7a5-bae7-4015-93f6-9d901085a3ac.PNG)


This plugin worked in smoothly in windows and linux .

But , it not worked in mac . it comes like this 

> I tried in github actions. it works smoothly in windows and linux.
> 
> but , it not worked in mac.
> 
> ![qt red mark](https://user-images.githubusercontent.com/88296348/133915023-e20241ca-5122-4d6c-a2f0-fe17461aadba.PNG)
> 
> how can I solve this ?

**Comment by axmetishe** [comment] 2021-09-20 19:58
@harideva16 thanks for the details, will check them.
Is this project available publicly for review purposes?

**Comment by harideva16** [comment] 2021-09-21 05:59
> @harideva16 thanks for the details, will check them.
> Is this project available publicly for review purposes?

I am really sorry , that project is not mine.

that project also contains some sensitive information about which company I working.

This plugin smoothly worked in windows and linux ?

why it not worked in mac ?

did you check this plugin in mac ?

Help me !!!

complete log

[2_macOS-latest.txt](https://github.com/axmetishe/gradle-qt-application-example/files/7200568/2_macOS-latest.txt)

**Comment by harideva16** [comment] 2021-09-21 11:49
**I am using**

- gradle version 7.0
- Java version 16.0.2
- QT - 5.15.2

How can I solve this error ?

**Comment by johnpawl** [comment] 2021-09-22 03:42
I think the problem is here :

    else if (compileTask.targetPlatform.get().operatingSystem.isMacOsX()) {
           compileTask.compilerArgs.add('-std=gnu++11')
    }

**Comment by johnpawl** [comment] 2021-09-22 09:31
same error : https://github.com/johnpawl/qt-github-action/runs/3673290798?check_suite_focus=true

**Comment by axmetishe** [comment] 2021-09-25 05:02
@harideva16 The initial request was related to incorrect CPP project compilation flags while the latter errors related to libraries handling inside the plugin.

Closing this since initial request resolved.
Please refer to https://github.com/axmetishe/gradle-qt-plugin/issues/13 for further details.

**Closed as completed by axmetishe** 2021-09-25 05:02 UTC
Labels: question
